-- Historial permanente de rendimiento por armado de pedidos.
-- Ejecutar una vez en Supabase SQL Editor.

create table if not exists public.rendimiento_pedidos (
  id bigint generated by default as identity primary key,
  pedido_id text not null,
  usuario_id text not null,
  usuario text,
  nombre text,
  tomado_en timestamptz,
  completado_en timestamptz not null default now(),
  duracion_segundos integer,
  articulos_distintos integer not null default 0,
  unidades_totales integer not null default 0,
  faltantes_distintos integer not null default 0,
  fecha date generated always as ((completado_en at time zone 'America/Montevideo')::date) stored,
  created_at timestamptz not null default now(),
  constraint rendimiento_pedidos_pedido_id_key unique (pedido_id)
);

create index if not exists rendimiento_pedidos_usuario_id_idx
  on public.rendimiento_pedidos (usuario_id);

create index if not exists rendimiento_pedidos_completado_en_idx
  on public.rendimiento_pedidos (completado_en desc);

create index if not exists rendimiento_pedidos_fecha_idx
  on public.rendimiento_pedidos (fecha desc);

create index if not exists rendimiento_pedidos_usuario_fecha_idx
  on public.rendimiento_pedidos (usuario_id, fecha desc);

alter table public.rendimiento_pedidos enable row level security;

-- No se crean políticas públicas: el panel accede a esta tabla únicamente
-- desde funciones del servidor usando SUPABASE_SERVICE_ROLE_KEY.

comment on table public.rendimiento_pedidos is
  'Historial permanente de pedidos armados por usuarios internos de Makabra.';
