-- Historial permanente de rendimiento por armado de pedidos.
-- Ejecutar una vez en Supabase SQL Editor.
-- Puede ejecutarse más de una vez.

create table if not exists public.rendimiento_pedidos (
  id bigint generated by default as identity primary key,
  pedido_id text not null,
  usuario_id text not null,
  usuario text,
  nombre text,
  tomado_en timestamptz,
  completado_en timestamptz not null default now(),
  duracion_segundos integer,
  articulos_distintos integer not null default 0,
  unidades_totales integer not null default 0,
  faltantes_distintos integer not null default 0,
  fecha date generated always as ((completado_en at time zone 'America/Montevideo')::date) stored,
  created_at timestamptz not null default now(),
  constraint rendimiento_pedidos_pedido_id_key unique (pedido_id)
);

create index if not exists rendimiento_pedidos_usuario_id_idx
  on public.rendimiento_pedidos (usuario_id);

create index if not exists rendimiento_pedidos_completado_en_idx
  on public.rendimiento_pedidos (completado_en desc);

create index if not exists rendimiento_pedidos_fecha_idx
  on public.rendimiento_pedidos (fecha desc);

create index if not exists rendimiento_pedidos_usuario_fecha_idx
  on public.rendimiento_pedidos (usuario_id, fecha desc);

alter table public.rendimiento_pedidos enable row level security;

-- No se crean políticas públicas: el panel accede a esta tabla únicamente
-- desde funciones del servidor usando SUPABASE_SERVICE_ROLE_KEY.

comment on table public.rendimiento_pedidos is
  'Historial permanente de pedidos armados por usuarios internos de Makabra.';

create or replace function public.makabra_rendimiento_empleados(
  p_desde timestamptz default null,
  p_hasta timestamptz default null
)
returns table (
  usuario_id text,
  usuario text,
  nombre text,
  pedidos integer,
  articulos bigint,
  unidades bigint,
  faltantes bigint,
  duracion_promedio_segundos integer,
  ultima_finalizacion timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    r.usuario_id,
    max(r.usuario) as usuario,
    max(r.nombre) as nombre,
    count(*)::integer as pedidos,
    coalesce(sum(r.articulos_distintos), 0)::bigint as articulos,
    coalesce(sum(r.unidades_totales), 0)::bigint as unidades,
    coalesce(sum(r.faltantes_distintos), 0)::bigint as faltantes,
    coalesce(round(avg(r.duracion_segundos))::integer, 0) as duracion_promedio_segundos,
    max(r.completado_en) as ultima_finalizacion
  from public.rendimiento_pedidos r
  where (p_desde is null or r.completado_en >= p_desde)
    and (p_hasta is null or r.completado_en < p_hasta)
  group by r.usuario_id
  order by count(*) desc, max(r.completado_en) desc;
$$;

revoke all on function public.makabra_rendimiento_empleados(timestamptz, timestamptz) from public;
grant execute on function public.makabra_rendimiento_empleados(timestamptz, timestamptz) to service_role;
