-- Panel operativo de pedidos Makabra
-- Los pedidos permanecen en el panel durante 24 horas desde el PRIMER ingreso.
-- Un nuevo pedido del mismo cliente registrado se suma al pedido activo sin reiniciar ese plazo.

begin;

-- La tabla pedidos ya existe. Se agregan únicamente los campos operativos faltantes.
alter table public.pedidos
  add column if not exists estado_armado text not null default 'pendiente',
  add column if not exists estado_facturacion text not null default 'pendiente',
  add column if not exists actualizaciones integer not null default 1,
  add column if not exists ultimo_ingreso_en timestamptz not null default now();

-- Asegura que order_id pueda utilizarse como referencia estable del pedido.
create unique index if not exists pedidos_order_id_unique_idx
  on public.pedidos (order_id);

create index if not exists pedidos_cliente_codigo_creado_idx
  on public.pedidos (cliente_codigo, creado_en desc);

create index if not exists pedidos_creado_en_idx
  on public.pedidos (creado_en desc);

-- Productos que deben prepararse para cada pedido.
create table if not exists public.pedido_items (
  id bigint generated by default as identity primary key,
  pedido_order_id text not null references public.pedidos(order_id) on delete cascade,
  producto_id text not null,
  producto_nombre text not null,
  cantidad integer not null check (cantidad > 0),
  precio_unitario_uyu integer not null default 0,
  subtotal_uyu integer not null default 0,
  consultable boolean not null default false,
  armado boolean not null default false,
  sector text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  unique (pedido_order_id, producto_id)
);

create index if not exists pedido_items_pedido_idx
  on public.pedido_items (pedido_order_id);

-- Registra cada envío del cliente para que una repetición de red no sume dos veces.
create table if not exists public.pedido_ingresos (
  order_id text primary key,
  pedido_order_id text not null references public.pedidos(order_id) on delete cascade,
  creado_en timestamptz not null default now()
);

create index if not exists pedido_ingresos_pedido_idx
  on public.pedido_ingresos (pedido_order_id);

-- Toda lectura y escritura pública queda bloqueada. Las API de Vercel usan service_role.
alter table public.pedido_items enable row level security;
alter table public.pedido_ingresos enable row level security;

revoke all on table public.pedido_items from anon, authenticated;
revoke all on table public.pedido_ingresos from anon, authenticated;

-- Valores válidos para los dos procesos que pueden trabajar en paralelo.
alter table public.pedidos
  drop constraint if exists pedidos_estado_armado_check;
alter table public.pedidos
  add constraint pedidos_estado_armado_check
  check (estado_armado in ('pendiente', 'armando', 'armado'));

alter table public.pedidos
  drop constraint if exists pedidos_estado_facturacion_check;
alter table public.pedidos
  add constraint pedidos_estado_facturacion_check
  check (estado_facturacion in ('pendiente', 'facturando', 'facturado'));

commit;

notify pgrst, 'reload schema';
