-- Panel operativo de pedidos Makabra — migración correctiva y no destructiva.
-- Puede ejecutarse más de una vez.
--
-- Corrige bases que todavía conservan columnas/tablas del esquema anterior,
-- por ejemplo codigo_pedido, items y articulos_de_pedido.
-- No elimina pedidos, clientes ni la tabla historica articulos_de_pedido.

begin;

-- ---------------------------------------------------------------------------
-- 1. Estructura canónica del pedido
-- ---------------------------------------------------------------------------

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  order_id text
);

alter table public.pedidos
  add column if not exists order_id text,
  add column if not exists cliente_id bigint,
  add column if not exists cliente_codigo varchar(7),
  add column if not exists cliente_clave text,
  add column if not exists cliente_nombre text,
  add column if not exists cliente_telefono text,
  add column if not exists estado text default 'pendiente',
  add column if not exists estado_armado text default 'pendiente',
  add column if not exists estado_facturacion text default 'pendiente',
  add column if not exists total_uyu integer default 0,
  add column if not exists tiene_consultables boolean default false,
  add column if not exists actualizaciones integer default 1,
  add column if not exists origen text default 'web_whatsapp',
  add column if not exists creado_en timestamptz default now(),
  add column if not exists actualizado_en timestamptz default now(),
  add column if not exists ultimo_ingreso_en timestamptz default now();

-- Recupera el identificador desde codigo_pedido cuando la tabla vieja lo tiene.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'pedidos'
      and column_name = 'codigo_pedido'
  ) then
    execute $sql$
      update public.pedidos
         set order_id = coalesce(
           nullif(btrim(order_id), ''),
           nullif(btrim(codigo_pedido::text), ''),
           'MK-LEGACY-' || id::text
         )
    $sql$;

    -- El código actual escribe order_id. La columna vieja no debe bloquear inserts.
    execute 'alter table public.pedidos alter column codigo_pedido drop not null';
  else
    update public.pedidos
       set order_id = coalesce(nullif(btrim(order_id), ''), 'MK-LEGACY-' || id::text);
  end if;
end
$$;

-- Normaliza identificadores heredados que no cumplen el formato usado por el panel.
update public.pedidos
   set order_id = 'MK-LEGACY-' || id::text
 where order_id is null
    or btrim(order_id) = ''
    or order_id !~* '^MK-[A-Z0-9-]+$';

-- Evita que datos heredados duplicados impidan crear el índice único.
with ranked as (
  select
    id,
    order_id,
    row_number() over (partition by order_id order by id) as position
  from public.pedidos
)
update public.pedidos as p
   set order_id = p.order_id || '-' || p.id::text
  from ranked as r
 where p.id = r.id
   and r.position > 1;

alter table public.pedidos
  alter column order_id set not null,
  alter column estado set default 'pendiente',
  alter column estado_armado set default 'pendiente',
  alter column estado_facturacion set default 'pendiente',
  alter column actualizaciones set default 1,
  alter column creado_en set default now(),
  alter column actualizado_en set default now(),
  alter column ultimo_ingreso_en set default now();

create unique index if not exists pedidos_order_id_unique_idx
  on public.pedidos (order_id);
create index if not exists pedidos_cliente_codigo_creado_idx
  on public.pedidos (cliente_codigo, creado_en desc);
create index if not exists pedidos_creado_en_idx
  on public.pedidos (creado_en desc);

-- Sincroniza codigo_pedido y order_id cuando la columna antigua todavía existe.
create or replace function public.makabra_sync_order_codes()
returns trigger
language plpgsql
as $$
begin
  if new.order_id is null or btrim(new.order_id) = '' then
    new.order_id := nullif(btrim(new.codigo_pedido::text), '');
  end if;

  if new.codigo_pedido is null or btrim(new.codigo_pedido::text) = '' then
    new.codigo_pedido := new.order_id;
  end if;

  return new;
end
$$;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'pedidos'
      and column_name = 'codigo_pedido'
  ) then
    execute 'drop trigger if exists makabra_sync_order_codes_trigger on public.pedidos';
    execute $sql$
      create trigger makabra_sync_order_codes_trigger
      before insert or update of order_id, codigo_pedido
      on public.pedidos
      for each row
      execute function public.makabra_sync_order_codes()
    $sql$;
  end if;
end
$$;

-- Elimina checks antiguos incompatibles y crea los checks del flujo nuevo.
do $$
declare
  current_constraint record;
begin
  for current_constraint in
    select conname
    from pg_constraint
    where conrelid = 'public.pedidos'::regclass
      and contype = 'c'
      and (
        pg_get_constraintdef(oid) ilike '%estado%'
        or pg_get_constraintdef(oid) ilike '%cliente_codigo%'
      )
  loop
    execute format(
      'alter table public.pedidos drop constraint if exists %I',
      current_constraint.conname
    );
  end loop;
end
$$;

update public.pedidos
   set estado = 'pendiente'
 where estado is null
    or estado not in (
      'pendiente', 'armando', 'armado', 'confirmado', 'preparando',
      'en_reparto', 'entregado', 'cancelado'
    );

update public.pedidos
   set estado_armado = 'pendiente'
 where estado_armado is null
    or estado_armado not in ('pendiente', 'armando', 'armado');

update public.pedidos
   set estado_facturacion = 'pendiente'
 where estado_facturacion is null
    or estado_facturacion not in ('pendiente', 'facturando', 'facturado');

update public.pedidos
   set cliente_codigo = null
 where cliente_codigo is not null
   and cliente_codigo !~ '^(?:[0-9]{5}|[0-9]{7})$';

update public.pedidos
   set actualizaciones = greatest(1, coalesce(actualizaciones, 1)),
       creado_en = coalesce(creado_en, now()),
       actualizado_en = coalesce(actualizado_en, creado_en, now()),
       ultimo_ingreso_en = coalesce(ultimo_ingreso_en, actualizado_en, creado_en, now());

alter table public.pedidos
  drop constraint if exists pedidos_estado_valido_panel;
alter table public.pedidos
  add constraint pedidos_estado_valido_panel
  check (
    estado in (
      'pendiente', 'armando', 'armado', 'confirmado', 'preparando',
      'en_reparto', 'entregado', 'cancelado'
    )
  );

alter table public.pedidos
  drop constraint if exists pedidos_estado_armado_check;
alter table public.pedidos
  add constraint pedidos_estado_armado_check
  check (estado_armado in ('pendiente', 'armando', 'armado'));

alter table public.pedidos
  drop constraint if exists pedidos_estado_facturacion_check;
alter table public.pedidos
  add constraint pedidos_estado_facturacion_check
  check (estado_facturacion in ('pendiente', 'facturando', 'facturado'));

alter table public.pedidos
  drop constraint if exists pedidos_cliente_codigo_panel_check;
alter table public.pedidos
  add constraint pedidos_cliente_codigo_panel_check
  check (cliente_codigo is null or cliente_codigo ~ '^(?:[0-9]{5}|[0-9]{7})$');

-- ---------------------------------------------------------------------------
-- 2. Productos que se preparan en el depósito
-- ---------------------------------------------------------------------------

create table if not exists public.pedido_items (
  id bigint generated by default as identity primary key,
  pedido_order_id text,
  producto_id text,
  producto_nombre text,
  cantidad integer default 1,
  precio_unitario_uyu integer default 0,
  subtotal_uyu integer default 0,
  consultable boolean default false,
  armado boolean default false,
  sector text,
  creado_en timestamptz default now(),
  actualizado_en timestamptz default now()
);

alter table public.pedido_items
  add column if not exists pedido_order_id text,
  add column if not exists producto_id text,
  add column if not exists producto_nombre text,
  add column if not exists cantidad integer default 1,
  add column if not exists precio_unitario_uyu integer default 0,
  add column if not exists subtotal_uyu integer default 0,
  add column if not exists consultable boolean default false,
  add column if not exists armado boolean default false,
  add column if not exists sector text,
  add column if not exists creado_en timestamptz default now(),
  add column if not exists actualizado_en timestamptz default now();

-- Descarta solamente filas inválidas de la tabla operativa nueva.
delete from public.pedido_items
 where pedido_order_id is null
    or producto_id is null;

-- Conserva una sola fila por producto si hubo una ejecución parcial previa.
delete from public.pedido_items as older
using public.pedido_items as newer
where older.ctid < newer.ctid
  and older.pedido_order_id = newer.pedido_order_id
  and older.producto_id = newer.producto_id;

create unique index if not exists pedido_items_order_product_unique_idx
  on public.pedido_items (pedido_order_id, producto_id);
create index if not exists pedido_items_pedido_idx
  on public.pedido_items (pedido_order_id);

-- Recupera productos guardados anteriormente dentro de pedidos.items o
-- pedidos.articulos. Si esas columnas no existen, to_jsonb simplemente devuelve null.
with legacy_rows as (
  select
    p.order_id,
    coalesce(to_jsonb(p) -> 'items', to_jsonb(p) -> 'articulos', '[]'::jsonb) as payload
  from public.pedidos as p
), expanded as (
  select
    l.order_id,
    element.item,
    element.position
  from legacy_rows as l
  cross join lateral jsonb_array_elements(
    case
      when jsonb_typeof(l.payload) = 'array' then l.payload
      else '[]'::jsonb
    end
  ) with ordinality as element(item, position)
), normalized as (
  select
    order_id,
    coalesce(
      nullif(item ->> 'productId', ''),
      nullif(item ->> 'producto_id', ''),
      nullif(item ->> 'id', ''),
      'legacy-' || md5(
        order_id || coalesce(item ->> 'name', item ->> 'nombre', 'Producto') || position::text
      )
    ) as producto_id,
    coalesce(
      nullif(item ->> 'name', ''),
      nullif(item ->> 'nombre', ''),
      'Producto sin nombre'
    ) as producto_nombre,
    case
      when replace(coalesce(item ->> 'qty', item ->> 'cantidad', ''), ',', '.')
           ~ '^[0-9]+([.][0-9]+)?$'
      then greatest(
        1,
        round(replace(coalesce(item ->> 'qty', item ->> 'cantidad'), ',', '.')::numeric)::integer
      )
      else 1
    end as cantidad,
    case
      when replace(
        coalesce(
          item ->> 'unitPriceRounded',
          item ->> 'precio_unitario_uyu',
          item ->> 'precio_unitario',
          item ->> 'precio',
          ''
        ),
        ',', '.'
      ) ~ '^[0-9]+([.][0-9]+)?$'
      then round(replace(
        coalesce(
          item ->> 'unitPriceRounded',
          item ->> 'precio_unitario_uyu',
          item ->> 'precio_unitario',
          item ->> 'precio'
        ),
        ',', '.'
      )::numeric)::integer
      else 0
    end as precio_unitario_uyu,
    case
      when replace(
        coalesce(item ->> 'subtotalRounded', item ->> 'subtotal_uyu', item ->> 'subtotal', ''),
        ',', '.'
      ) ~ '^[0-9]+([.][0-9]+)?$'
      then round(replace(
        coalesce(item ->> 'subtotalRounded', item ->> 'subtotal_uyu', item ->> 'subtotal'),
        ',', '.'
      )::numeric)::integer
      else 0
    end as subtotal_uyu,
    lower(coalesce(item ->> 'consultable', 'false')) in ('true', 't', '1', 'si', 'sí')
      as consultable,
    coalesce(
      nullif(item ->> 'sector', ''),
      nullif(item ->> 'category', ''),
      nullif(item ->> 'categoria', '')
    ) as sector
  from expanded
)
insert into public.pedido_items (
  pedido_order_id,
  producto_id,
  producto_nombre,
  cantidad,
  precio_unitario_uyu,
  subtotal_uyu,
  consultable,
  armado,
  sector,
  actualizado_en
)
select
  order_id,
  producto_id,
  producto_nombre,
  cantidad,
  precio_unitario_uyu,
  case
    when subtotal_uyu > 0 then subtotal_uyu
    else precio_unitario_uyu * cantidad
  end,
  consultable or precio_unitario_uyu <= 0,
  false,
  sector,
  now()
from normalized
on conflict (pedido_order_id, producto_id)
do update set
  producto_nombre = excluded.producto_nombre,
  cantidad = excluded.cantidad,
  precio_unitario_uyu = excluded.precio_unitario_uyu,
  subtotal_uyu = excluded.subtotal_uyu,
  consultable = excluded.consultable,
  sector = coalesce(public.pedido_items.sector, excluded.sector),
  actualizado_en = now();

-- ---------------------------------------------------------------------------
-- 3. Control de reintentos y segundos pedidos
-- ---------------------------------------------------------------------------

create table if not exists public.pedido_ingresos (
  order_id text,
  pedido_order_id text,
  creado_en timestamptz default now()
);

alter table public.pedido_ingresos
  add column if not exists order_id text,
  add column if not exists pedido_order_id text,
  add column if not exists creado_en timestamptz default now();

delete from public.pedido_ingresos
 where order_id is null
    or pedido_order_id is null;

delete from public.pedido_ingresos as older
using public.pedido_ingresos as newer
where older.ctid < newer.ctid
  and older.order_id = newer.order_id;

create unique index if not exists pedido_ingresos_order_unique_idx
  on public.pedido_ingresos (order_id);
create index if not exists pedido_ingresos_pedido_idx
  on public.pedido_ingresos (pedido_order_id);

-- Marca como procesados los pedidos que ya estaban almacenados.
insert into public.pedido_ingresos (order_id, pedido_order_id, creado_en)
select order_id, order_id, coalesce(creado_en, now())
from public.pedidos
where order_id is not null
on conflict (order_id) do nothing;

-- ---------------------------------------------------------------------------
-- 4. Seguridad y permisos de la API del servidor
-- ---------------------------------------------------------------------------

alter table public.pedido_items enable row level security;
alter table public.pedido_ingresos enable row level security;

revoke all on table public.pedido_items from anon, authenticated;
revoke all on table public.pedido_ingresos from anon, authenticated;

grant select, insert, update, delete on table public.pedidos to service_role;
grant select, insert, update, delete on table public.pedido_items to service_role;
grant select, insert, update, delete on table public.pedido_ingresos to service_role;
grant usage, select, update on all sequences in schema public to service_role;

commit;

notify pgrst, 'reload schema';
