-- Pedidos generados desde la web antes de abrir WhatsApp.
-- Ejecutar una vez desde el SQL Editor de Supabase.

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  cliente_id bigint references public.clientes(id)
    on update cascade
    on delete set null,
  cliente_codigo varchar(7),
  cliente_clave text not null,
  cliente_nombre text,
  cliente_direccion text,
  cliente_telefono text,
  estado text not null default 'pendiente',
  total_uyu integer not null default 0,
  tiene_consultables boolean not null default false,
  items jsonb not null default '[]'::jsonb,
  mensaje text,
  origen text not null default 'web_whatsapp',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),

  constraint pedidos_cliente_codigo_formato
    check (cliente_codigo is null or cliente_codigo ~ '^[0-9]{7}$'),
  constraint pedidos_estado_valido
    check (estado in ('pendiente', 'confirmado', 'preparando', 'en_reparto', 'entregado', 'cancelado')),
  constraint pedidos_total_no_negativo
    check (total_uyu >= 0),
  constraint pedidos_items_array
    check (jsonb_typeof(items) = 'array')
);

create index if not exists pedidos_cliente_codigo_idx
  on public.pedidos (cliente_codigo);

create index if not exists pedidos_estado_idx
  on public.pedidos (estado);

create index if not exists pedidos_creado_en_idx
  on public.pedidos (creado_en desc);

alter table public.pedidos enable row level security;

-- Solo los endpoints del servidor escriben/leen pedidos.
grant select, insert, update, delete
on table public.pedidos
 to service_role;

grant usage, select, update
on all sequences in schema public
 to service_role;
