-- Tabla de clientes de reparto de Mayorista Makabra.
-- La API usa la service role; no se expone lectura pública de esta tabla.

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  codigo varchar(5) not null unique,
  nombre text not null,
  direccion text not null,
  telefono text not null,
  tipo text not null default 'reparto',
  activo boolean not null default true,
  observaciones text,
  origen text not null default 'google_sheets',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),

  constraint clientes_codigo_formato
    check (codigo ~ '^[0-9]{5}$'),
  constraint clientes_tipo_valido
    check (tipo in ('reparto', 'normal'))
);

create index if not exists clientes_activo_idx
  on public.clientes (activo);

create index if not exists clientes_nombre_idx
  on public.clientes (nombre);

create or replace function public.set_clientes_actualizado_en()
returns trigger
language plpgsql
as $$
begin
  new.actualizado_en = now();
  return new;
end;
$$;

drop trigger if exists clientes_set_actualizado_en on public.clientes;

create trigger clientes_set_actualizado_en
before update on public.clientes
for each row
execute function public.set_clientes_actualizado_en();

alter table public.clientes enable row level security;

comment on table public.clientes is
  'Clientes identificados para reparto y validación mediante código de 5 dígitos.';
